
FACIAL_EXPRESSIONS = [
    'DEFAULT',
    'ANGRY',
    'ANGRY_NATURAL',
    'DEFAULT_NATURAL',
    'FLAT_NATURAL',
    'FROWN_NATURAL',
    'RAISED_EXCITED',
    'RAISED_EXCITED_NATURAL',
    'SAD_CONCERNED',
    'SAD_CONCERNED_NATURAL',
    'UNI_BROW_NATURAL',
    'UP_DOWN',
    'UP_DOWN_NATURAL',
]

FACIAL_EXPRESSIONS_MOUTH = [
    'DEFAULT',
    'CONCERNED',
    'DISBELIEF',
    'EATING',
    'GRIMACE',
    'SAD',
    'SCREAM_OPEN',
    'SERIOUS',
    'SMILE',
    'TONGUE',
    'TWINKLE',
    'VOMIT',
]